services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  product-service:
    container_name: product-service
    build: ./product-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    networks:
      - micrommerce-network

  inventory-service:
    container_name: inventory-service
    build: ./inventory-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    networks:
      - micrommerce-network

  order-service:
    container_name: order-service
    build: ./order-service
    ports:
      - "8085:8085"
    depends_on:
      - kafka
    networks:
      - micrommerce-network

  payment-service:
    container_name: payment-service
    build: ./payment-service
    ports:
      - "8086:8086"
    depends_on:
      - kafka
    networks:
      - micrommerce-network

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - inventory-service
      - order-service
      - payment-service
    networks:
      - micrommerce-network

  eureka-server:
    container_name: eureka-server
    build: ./eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - product-service
      - inventory-service
      - order-service
      - payment-service
      - api-gateway
    networks:
      - micrommerce-network

  auth-service:
    container_name: auth-service
    build: ./auth-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - micrommerce-network

networks:
  micrommerce-network:
