version: '3.8'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  auth-service:
    build: ./auth-service
    depends_on:
      - eureka-server

  order-service:
    build: ./order-service
    depends_on:
      - eureka-server

networks:
  default:
    name: spring-network
