services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka

  inventory-service:
    build: ./inventory-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka

  order-service:
    build: ./order-service
    ports:
      - "8085:8085"
    depends_on:
      - kafka

  payment-service:
    build: ./payment-service
    ports:
      - "8086:8086"
    depends_on:
      - kafka