spring:
  # DATASOURCE
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: rW4HVG1r?4bI

  # JPA, SQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka