spring:
  application:
    name: inventory-service
  profiles:
    active: dev
  jpa:
    open-in-view: true

# SERVER
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka