server:
  port: 8081

spring:
  application:
    name: auth-service
  profiles:
    active: dev
  jpa:
    open-in-view: true

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/